# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: sreucherand/circleci-node-ffmpeg:0.0.1
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run: yarn test

      - run: yarn static

      - persist_to_workspace:
          root: ~/repo
          paths:
            - public

  deploy:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ./generated-site

      - run:
          command: sudo pip install awscli

      - run:
          command: aws s3 sync generated-site/public/ "s3://${BUCKET}/" --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
